#!/usr/bin/env bash
# Run inside the app container: docker compose exec app bash demo.sh
set -euo pipefail

separator() {
    echo
    echo "=============================================================="
    echo "  $1"
    echo "=============================================================="
    echo
}

# Reset state so the demo is repeatable.
cp app/models_initial.py app/models.py
find alembic/versions -name "*_add_tags_table.py" -delete || true


separator "STEP 1 — alembic current  (expect: empty / no current revision)"
alembic current || true


separator "STEP 2 — alembic history  (expect: 0001 -> 0002 -> 0003 head)"
alembic history


separator "STEP 3 — alembic upgrade head  (apply pre-authored migrations)"
alembic upgrade head


separator "STEP 4 — alembic current  (expect: 0003 (head))"
alembic current


separator "STEP 5 — psql \\dt  (expect: users, posts, alembic_version)"
PGPASSWORD="${POSTGRES_PASSWORD}" psql \
    -h db -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" \
    -c "\dt" || true


separator "STEP 6 — Stage the model edit (copy models_with_tag.py over models.py)"
cp app/models_with_tag.py app/models.py
echo "models.py now contains the Tag class. Diff (head):"
grep -n "class Tag" app/models.py || true


separator "STEP 7 — alembic revision --autogenerate -m 'add tags table'"
alembic revision --autogenerate -m "add tags table"


separator "STEP 8 — Show the generated migration file"
ls alembic/versions/*_add_tags_table.py
echo
cat alembic/versions/*_add_tags_table.py


separator "STEP 9 — alembic upgrade head  (apply the new autogenerated migration)"
alembic upgrade head


separator "STEP 10 — alembic downgrade -1  (roll the new migration back)"
alembic downgrade -1


separator "STEP 11 — alembic history --verbose  (final state)"
alembic history --verbose


separator "DEMO COMPLETE — schema is back at revision 0003 (head)"
